global:
  qsname: quickstart-mongodb
  reporting: true
  cis3bucket:  s3://quickstart-ci-bucket
  regions:
    - us-east-1

tests:
  qs_mongod-us-west-1:
    template_file:  MongoDB-VPC.template
    parameter_input: MongoDB-VPC-us-west-1.json
    regions:
    - us-west-1
