global:
  qsname: quickstart-mongodb
  owner: shukvino@amazon.com
  s3bucket: cfautomated
  reporting: true
  regions:
    - ap-northeast-1
    - ap-northeast-2
    - ap-south-1
    - ap-southeast-1
    - ap-southeast-2
    - ca-central-1
    - eu-central-1
    - eu-west-1
    - eu-west-2
    - sa-east-1
    - us-east-1
    - us-east-2
    - us-west-1
    - us-west-2
tests:
  mongodb-3-AZ:
    template_file:  mongodb-master.template
    parameter_input: mongodb-master.json
    regions:
    - ap-southeast-2
    - eu-west-1
    - us-east-1
    - us-east-2
    - us-west-2
  mongodb-2-AZ:
    template_file:  mongodb-master.template
    parameter_input: mongodb-master-2AZ.json
    regions:
      - ap-northeast-1
      - ap-northeast-2
      - ap-south-1
      - ap-southeast-1
      - ca-central-1
      - eu-central-1
      - eu-west-2
      - sa-east-1
      - us-west-1

